### PR TITLE
【Hackathon 5th No.99】RFC for developing SNPE RMSNorm OP

### PR DESCRIPTION
**Pull request by unseenme**

### CODE REVIEW

**Comment by unseenme** [comment]
@Ligoml @luotao1 请问这个RFC算是通过了吗？

**Comment by chenwu195** [comment]
@unseenme look good to me, please go ahead.

**Review by onecatcn — APPROVED** [review]
LGTM

**Comment by unseenme** [comment]
> @unseenme look good to me, please go ahead.

Thank you~

**Pull request merged**
